### PR TITLE
Procedures of the referenceScan table were modified

### PR DESCRIPTION
**Pull request by samo38**
- Procedures of the referenceScan table were modified

### CODE REVIEW

**Comment by demeler** [comment]
Emre,
what branch is used on demeler9? I don't see the merged changes there.
-b.

**Comment by demeler** [comment]
Saeed, do the changes you committed include the program for Amy? I don't see it in the code. Can you please make sure everything is committed for Emre to merge?
Thanks, -Borries

**Comment by samo38** [comment]
At the moment I only committed the DB table and its corresponding procedures and haven't executed it on uslims3_CCH. Because I have defined two connectors in the pseudo-absorbance program that one of them connects to uslims3_CCH and another one to my localhost, I need to refine a few lines of code to make sure that the program could communicate with uslims properly. So I am waiting for these changes to be merged to DB, then I will do a pull request for the pseudo-absorbance program to be merged to the master branch.
Thanks, -Saeed

**Comment by samo38** [comment]
Yes, of course, I'll do it tonight. -s

**Comment by ehb54** [comment]
Conversation moved to https://github.com/ehb54/ultrascan-tickets/issues/96
Conversation here locked.

**Pull request merged**
