### PR TITLE
Alexey dev for issue367: SQL changes for Data-from-Disk Integration

### PR DESCRIPTION
**Pull request by alexsav815**

### CODE REVIEW

**Comment by ehb54** [comment]
@alexsav815 

In us3_sql, on autoflow & autoflowHistory, you added an enum dataSource to each.
Can you give these a default value (assume it would be 'INSTRUMENT')?
This will prevent upgrade from breaking and requiring special handling.

Thanks.

**Comment by alexsav815** [comment]
Not at home now, but the default is 'not null', meaning it always be the first one on the list (the 'instrument').Or what default value are you talking about?In upgrade, I see, how it's done exactly?There will be more work in the code and stored procs if I to specify this specifically Sent from my Galaxy
-------- Original message --------From: ehb54 ***@***.***> Date: 12/8/24  4:05 PM  (GMT-06:00) To: ehb54/us3_sql ***@***.***> Cc: alexsav815 ***@***.***>, Mention ***@***.***> Subject: Re: [ehb54/us3_sql] Alexey dev for issue367: SQL changes for Data-from-Disk Integration (PR #14) 
@alexsav815
In us3_sql, on autoflow & autoflowHistory, you added an enum dataSource to each.
Can you give these a default value (assume it would be 'INSTRUMENT')?
This will prevent upgrade from breaking and requiring special handling.
Thanks.

**Comment by alexsav815** [comment]
Will DEFAULT 'INSTRUMENT' instead of NOT NULL help with your upgrades?Sent from my Galaxy
-------- Original message --------From: ehb54 ***@***.***> Date: 12/8/24  4:05 PM  (GMT-06:00) To: ehb54/us3_sql ***@***.***> Cc: alexsav815 ***@***.***>, Mention ***@***.***> Subject: Re: [ehb54/us3_sql] Alexey dev for issue367: SQL changes for Data-from-Disk Integration (PR #14) 
@alexsav815
In us3_sql, on autoflow & autoflowHistory, you added an enum dataSource to each.
Can you give these a default value (assume it would be 'INSTRUMENT')?
This will prevent upgrade from breaking and requiring special handling.
Thanks.

**Comment by ehb54** [comment]
I think that will do it, something to give a value to the preexisting records when not explicitly known.
We should in general always have a default for enums, but I'm only really watching this on new columns we add to the tables,
as it has caused upgrade hassles.

**Comment by ehb54** [comment]
I'm going to take back the "in general", it's useful to have the default "not null" as it forces a value to be set. It's just a hassle during upgrades if they are not set, we need to determine what value preexisting rows need and manually update. So as a convenience for this upgrade, please add a default "INSTRUMENT" to those modified tables.

**Comment by alexsav815** [comment]
Ok, so I will put DEFAULT 'INSTRUMENT' for now, and after upgrade we will put back NOT NULL ?

**Comment by alexsav815** [comment]
Actually, I need one more value in that enum dataSource (to address Simulated RA datatype).
Will make change

**Review by ehb54 — APPROVED** [review]

**Comment by ehb54** [comment]
Sorry, already merged it. After you make your change, you will need to make a new pull request off this same branch.
If I make it, I can't review it, so you will need to.

**Comment by alexsav815** [comment]
That's OK, I actually was able to deal with existing enumerators. 
Borries, I cleared the 4. EDIT stage for your RA-S run (no crash and it computes meniscus and all stuff)

Most likely, similar changes will be needed for ANALYSIS and possibly for REPORTING. 
Working on it

Emre, I still use that branch (in ehb54/ultrasca3 repo, alexey-dev-issue367) - was it deleted with the merge?

**Comment by ehb54** [comment]
> Emre, I still use that branch (in ehb54/ultrasca3 repo, alexey-dev-issue367) - was it deleted with the merge?

No, I left it.

**Pull request merged**
