### PR TITLE
Storing cosedimenting components in the database

### PR DESCRIPTION
**Pull request by doluk**

### CODE REVIEW

**Comment by ehb54** [comment]
@doluk This PR should be on the master branch, not the release branch.

**Comment by ehb54** [comment]
@doluk Also curious, did you intentionally change the double quotes to single quotes in the autoflow tables? It's ok, probably good for consistency, but wondering if you did it intentionally.

**Comment by doluk** [comment]
Yes, it was intentionally because my IDE was upset with the the doubled ones. I guess I wanted it to change it back but forget it. I will "fix" it after the lunch

**Comment by doluk** [comment]
> @doluk This PR should be on the master branch, not the release branch.
> 
 okay I will change it too

**Comment by ehb54** [comment]
> Yes, it was intentionally because my IDE was upset with the the doubled ones. I guess I wanted it to change it back but forget it. I will "fix" it after the lunch

Just leave it as single quotes, I think keeping the single quotes is better for consistency.

**Comment by demeler** [comment]
We need to keep the co-sedimentation code separate from any release
branches until it has received very thorough review because any change in
the buffer calculations or finite element calculations could have
detrimental effects on reproducibility, which is of utmost importance to
our clients.

**Comment by doluk** [comment]
> We need to keep the co-sedimentation code separate from any release branches until it has received very thorough review because any change in the buffer calculations or finite element calculations could have detrimental effects on reproducibility, which is of utmost importance to our clients.
> 
 of course, my bad. I created the new pull request to the correct branch already #2

**Pull request closed without merging**
